### ISSUE TITLE
Sync with similar package authors

### ISSUE THREAD

**Issue by brev** [sebamarynissen/node-esm-loader#1]
Hi, thanks for the great package. I've been very excited about something like this, and was glad to find it.

I've noticed a few similar efforts, and just wanted to let you know, in case you hadn't seen them before. These are both still on the old API (Node.js, pre-16.12):
- https://github.com/lukeed/loadr
- https://www.npmjs.com/package/esm-loader-chaining-polyfill

Now hopefully everyone will upgrade to 16.12 API so I can use this. :)

**Comment by sebamarynissen** [comment]
Hi there, thanks for reaching out! Could you clarify perhaps what your setup is? Since you mentioned in https://github.com/lukeed/loadr/issues/2#issuecomment-975144925 that it is not working for you, maybe I can help you out with the configuration.
