### ISSUE TITLE
We can use this with webpack?

### ISSUE THREAD

**Issue by Kali95739** [sebamarynissen/node-esm-loader#4]

**Comment by Kali95739** [comment]
To resolve a builtin like fs?

**Comment by Kali95739** [comment]
@sebamarynissen

**Comment by sebamarynissen** [comment]
No, this is a module that can be used to `import` non-js files in Node by using a configuration that is *inspired* by how webpack does it. More specifically, it makes it easier to compose loaders (see also https://nodejs.org/api/esm.html#loaders).

If you want to resolve Node builtins with webpack, you need to use the `fallback` config: https://webpack.js.org/configuration/resolve/#resolvefallback
